export type LuxuryProduct = {
  id: string;
  name: string;
  category: string;
  description: string;
  image: string;
  keywords: string[];
  material: string;
  pricing: string;
  useCase: string;
};

export const luxuryCategories = [
  "Shirts & Blouses",
  "Suits & Tailoring",
  "Dresses & Gowns",
  "Outerwear & Coats",
  "Knitwear & Cashmere",
  "Denim & Casual",
  "Footwear",
  "Handbags",
  "Accessories",
  "Lingerie & Sleepwear",
];

export const luxuryProducts: LuxuryProduct[] = [
  {
    id: "luxury-shirt-boxes",
    name: "Luxury Shirt Boxes",
    category: "Shirts & Blouses",
    description: "Crisp-fold boxes with collar guards and tissue wrap for luxury shirts.",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=300&fit=crop",
    keywords: ["shirts", "boxes", "collar", "folded", "premium", "luxury"],
    material: "Rigid board + tissue",
    pricing: "Custom quote",
    useCase: "Luxury shirts",
  },
  {
    id: "silk-blouse-folios",
    name: "Silk Blouse Folios",
    category: "Shirts & Blouses",
    description: "Slim folio-style packs that protect silk blouses without creasing.",
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=400&h=300&fit=crop",
    keywords: ["blouse", "silk", "folio", "folded", "delicate", "premium"],
    material: "Soft-touch board",
    pricing: "Custom quote",
    useCase: "Silk blouses",
  },
  {
    id: "tailored-suit-garment-bags",
    name: "Tailored Suit Garment Bags",
    category: "Suits & Tailoring",
    description: "Breathable garment bags that keep tailored suits crease-free.",
    image: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop",
    keywords: ["suits", "garment", "bags", "tailored", "menswear", "premium"],
    material: "Reinforced fabric",
    pricing: "Custom quote",
    useCase: "Tailored suits",
  },
  {
    id: "rigid-suit-presentation-boxes",
    name: "Rigid Suit Presentation Boxes",
    category: "Suits & Tailoring",
    description: "Premium rigid boxes for statement suiting and couture menswear.",
    image: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=300&fit=crop",
    keywords: ["suits", "presentation", "boxes", "luxury", "tailoring"],
    material: "Rigid board + liner",
    pricing: "Custom quote",
    useCase: "Suit presentations",
  },
  {
    id: "evening-gown-boxes",
    name: "Evening Gown Boxes",
    category: "Dresses & Gowns",
    description: "Large-format boxes with padding to protect embellished gowns.",
    image: "https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=400&h=300&fit=crop",
    keywords: ["gown", "dress", "boxes", "evening", "formal", "embellished"],
    material: "Padded rigid board",
    pricing: "Custom quote",
    useCase: "Evening gowns",
  },
  {
    id: "cocktail-dress-packaging",
    name: "Cocktail Dress Packaging",
    category: "Dresses & Gowns",
    description: "Structured packaging that preserves shape and luxury finishes.",
    image: "https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=400&h=300&fit=crop",
    keywords: ["dress", "cocktail", "boxes", "structured", "luxury"],
    material: "Textured board",
    pricing: "Custom quote",
    useCase: "Cocktail dresses",
  },
  {
    id: "outerwear-garment-covers",
    name: "Outerwear Garment Covers",
    category: "Outerwear & Coats",
    description: "Protective covers for coats and jackets with dust and moisture control.",
    image: "https://images.unsplash.com/photo-1578662996442-48f60103fc96?w=400&h=300&fit=crop",
    keywords: ["outerwear", "coats", "covers", "garment", "protection"],
    material: "Laminated fabric",
    pricing: "Custom quote",
    useCase: "Luxury outerwear",
  },
  {
    id: "leather-jacket-cases",
    name: "Leather Jacket Cases",
    category: "Outerwear & Coats",
    description: "Protective cases with breathable liners for leather outerwear.",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop",
    keywords: ["leather", "jacket", "cases", "outerwear", "premium"],
    material: "Cotton + microfiber",
    pricing: "Custom quote",
    useCase: "Leather jackets",
  },
  {
    id: "cashmere-fold-boxes",
    name: "Cashmere Fold Boxes",
    category: "Knitwear & Cashmere",
    description: "Soft-lined boxes that keep knitwear plush and pill-free.",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=300&fit=crop",
    keywords: ["cashmere", "knitwear", "boxes", "folded", "premium"],
    material: "Soft-touch board",
    pricing: "Custom quote",
    useCase: "Cashmere knits",
  },
  {
    id: "designer-denim-fold-sets",
    name: "Designer Denim Fold Sets",
    category: "Denim & Casual",
    description: "Fold sets with branded tissue and inserts for premium denim.",
    image: "https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=300&fit=crop",
    keywords: ["denim", "fold", "sets", "premium", "casual"],
    material: "Recycled board",
    pricing: "Custom quote",
    useCase: "Designer denim",
  },
  {
    id: "luxury-shoe-boxes",
    name: "Luxury Shoe Boxes",
    category: "Footwear",
    description: "Structured shoe boxes with dust bags and protective inserts.",
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop",
    keywords: ["shoes", "boxes", "footwear", "luxury", "inserts"],
    material: "Rigid board",
    pricing: "Custom quote",
    useCase: "Luxury footwear",
  },
  {
    id: "handbag-dust-bags-boxes",
    name: "Handbag Dust Bags & Boxes",
    category: "Handbags",
    description: "Luxury dust bags paired with rigid boxes for premium handbags.",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=400&h=300&fit=crop",
    keywords: ["handbags", "dust bags", "boxes", "luxury", "premium"],
    material: "Cotton + rigid board",
    pricing: "Custom quote",
    useCase: "Handbags",
  },
  {
    id: "accessory-cases",
    name: "Jewelry & Accessory Cases",
    category: "Accessories",
    description: "Compact cases that secure fine accessories and jewelry pieces.",
    image: "https://images.unsplash.com/photo-1518544801976-3e159e50e5bb?w=400&h=300&fit=crop",
    keywords: ["accessories", "jewelry", "cases", "premium", "compact"],
    material: "Textured board",
    pricing: "Custom quote",
    useCase: "Accessories",
  },
  {
    id: "lingerie-drawer-boxes",
    name: "Lingerie Drawer Boxes",
    category: "Lingerie & Sleepwear",
    description: "Soft-structured boxes for delicate lingerie and sleepwear sets.",
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?w=400&h=300&fit=crop",
    keywords: ["lingerie", "sleepwear", "boxes", "delicate", "premium"],
    material: "Soft-touch board",
    pricing: "Custom quote",
    useCase: "Lingerie sets",
  },
];

export const getLuxuryProductById = (id: string) =>
  luxuryProducts.find((product) => product.id === id);

